### PR TITLE
Add tests cases for network interfaces

### PR DESCRIPTION
**Pull request by LuKks**

### CODE REVIEW

**Comment by mafintosh** [comment]
unsure about the _onevent stuff (in terms of brittleness) so pinging @kasperisager for a second opinion

**Comment by kasperisager** [comment]
This does seem to be exercising the internals a bit too closely. Can we make it more general?

**Comment by LuKks** [comment]
`udx_napi_interface_event_init` registers `_onevent`, but since it's difficult, or unknown to me, cross-platform to fire a network change event. `_onevent` will be left untested as it's true that is playing too much with the internals

**Comment by mafintosh** [comment]
@LuKks ya, might be one for those things we just test manually, for simplicity

**Comment by mafintosh** [comment]
concern is that calling an internal isn't really defined, so doesn't really test much in practice. and spinning interfaces up/down obvs is way to complex, so pragmatism has to win. let me think about it tho.

**Comment by LuKks** [comment]
Yea, I also tested it on Windows manually, works great

**Comment by LuKks** [comment]
I think I might have to add the async back to the destroy method

**Comment by LuKks** [comment]
Or maybe not, as this doesn't have it:
https://github.com/hyperswarm/libudx/blob/a4d4befbfa859f1dc375f00c4e44091f5fa79404/lib/udx.js#L47
And both seems safe, unless `udx_napi_interface_event_close` or `udx_napi_lookup` could throw in place?

Just bringing this up as I wrongly removed the async in the `send` method in other PR.

**Comment by kasperisager** [comment]
@LuKks The `async` should be there. I've also added it to `lookup()` to ensure that thrown errors cause promise rejections: https://github.com/hyperswarm/libudx/pull/97/files#diff-3c28d0996a1926ebf996ef12f820dfaea21b4c515d2fb526ca64d5b467955c32R46

**Comment by mafintosh** [comment]
Good pragmatic test in the end 👍

**Pull request merged**
