### PR TITLE
Add `opts.framed` to enable framed mode

### PR DESCRIPTION
**Pull request by kasperisager**

### CODE REVIEW

**Comment by mafintosh** [comment]
@kasperisager what are we missing here?

**Comment by kasperisager** [comment]
@mafintosh Contingencies in case of frames that don't start at the beginning of a transmission unit, _if_ we expect that to occur. I'd say we perhaps land this first and try it out?

**Comment by mafintosh** [comment]
@kasperisager good to go?

**Comment by kasperisager** [comment]
@mafintosh Yep!

**Comment by mafintosh** [comment]
@kasperisager we don't need the mode to be a bitfield actually - all the modes are unique

0: default (just bubble everything up)
1: non-interactive (buffer as much as possible - ie a file download etc)
2: framed (buffer 24bit frames if posssible)

**Comment by kasperisager** [comment]
@mafintosh Great point, adjusted that 👍

**Pull request merged**
